[1주차: 변수] 4장. 변수
Endless-Creation-32nd/javascript-deep-dive pull request #1
Opened 2022-10-07 11:55 UTC by sjsjsj1246

04장: 변수

4.1 변수란 무엇인가? 왜 필요한가?
4.2 식별자
4.3 변수 선언
4.4 변수 선언의 실행 시점과 변수 호이스팅
4.5 값의 할당
4.6 값의 재할당
4.7 식별자 네이밍 규칙

2022-10-12 11:05 UTC, ojj1123 requested changes

2022-10-12 11:05 UTC, ojj1123 commented on 04장-변수/README.md
> +# 4장: 변수
오 이거 하나 지워도 될듯!

2022-10-12 11:06 UTC, sjsjsj1246 commented on 04장-변수/README.md
> +# 4장: 변수
아하 노션에 정리하고 복붙하느라 하나 더 추가됐네요

2022-10-14 02:33 UTC, Sangjun-man commented
정리된 글 읽어보다가 LHS Lookup 이라는 단어가 뭔지 몰라서 찾아봤는데,
LHS Lookup은 값을 할당하기 위해 메모리 주소값을 찾는것이고
RHS Lookup은 이미 저장된 값을 얻기 위해 메모리 주소를 참조하는거라고 이해해도 될까요???
컴파일러 구조 수업에서 하나여,, 수업을 안들어서 모르겠습니다

2022-10-14 03:56 UTC, ojj1123 approved these changes

2022-10-14 04:06 UTC, sjsjsj1246 commented
> 정리된 글 읽어보다가 LHS Lookup 이라는 단어가 뭔지 몰라서 찾아봤는데, LHS Lookup은 값을 할당하기 위해 메모리 주소값을 찾는것이고 RHS Lookup은 이미 저장된 값을 얻기 위해 메모리 주소를 참조하는거라고 이해해도 될까요??? 컴파일러 구조 수업에서 하나여,, 수업을 안들어서 모르겠습니다

@Sangjun-man 네 그렇게 이해하시면 됩니다. 수업에서 다룬 내용은 참고하지 않았습니다. 수업에 안나옵니다.

2022-10-14 04:47 UTC, ojj1123 commented on 04장-변수/README.md
> +`변수에 값을 재할당`할때는 처음에 변수에 값을 할당할 때처럼 이전 값이 저장되어 있던 메모리 공간에 새로운 값을 저장하는 것이 아니라 `새로운 메모리 공간`을 확보하고 그 `메모리 공간에 새로운 값을 저장하는 것`이다.
아직 책을 안읽어봐서 이 문장이 잘 안 와닿는데, 재할당이라는게
```js
let foo = 1;

foo = 2; // 이걸 재할당이라고 하는거는 맞을거고!
```
재할당이라면 그냥 그 메모리에 값이 할당이 되는거로 알고 있었는데,
메모리 공간이 새로 만들어지는거가 왜 잘 안받아들여지지;;

혹시 책에 자세히 나와있나요?

2022-10-14 06:51 UTC, sjsjsj1246 commented on 04장-변수/README.md
> +`변수에 값을 재할당`할때는 처음에 변수에 값을 할당할 때처럼 이전 값이 저장되어 있던 메모리 공간에 새로운 값을 저장하는 것이 아니라 `새로운 메모리 공간`을 확보하고 그 `메모리 공간에 새로운 값을 저장하는 것`이다.
책에는 자세히 나와있지 않지만 자바스크립트에서 재할당을 할 때는 기존에 있던 메모리 공간에 값을 할당하지 않습니다.

만약 기존에 있던 메모리 공간의 크기가 할당할 값보다 작다면 그 메모리를 늘려주는 작업도 해야 할 겁니다. 비용이 많이 들죠 그렇지 않고 다른 메모리 공간에 값을 저장해놓고 식별자 foo는 그 메모리 공간을 가리키기만 하면 되겠죠

즉 메모리의 효율적인 처리를 위해 이런 동작을 하고 재할당이 일어날 때 마다 새로운 메모리 공간을 할당하며 기존에 있던 메모리 공간은 가비지 컬렝터의 대상이 됩니다

2022-10-14 15:34 UTC, merged